Output tapes/screenshots/check-health-large.gif

Set Shell "zsh"
Set Width 1600
Set Height 1000
Set FontSize 18
Set Theme "Catppuccin Mocha"

Type "DOPS_NO_ALT_SCREEN=1 ./dops"
Enter
Sleep 2s

Enter
Sleep 1s
Type "google.com"
Sleep 300ms
Enter
Sleep 3s

Screenshot tapes/screenshots/check-health-large.png

Tab
Sleep 300ms
Up
Sleep 300ms
Up
Sleep 300ms

Screenshot tapes/screenshots/check-health-large-scrolled.png

Type "q"
Sleep 500ms
